spring.application.name=dimdim-cloud
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:ddl.sql
spring.sql.init.separator=GO
spring.sql.init.continue-on-error=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
server.error.include-message=never
server.error.include-stacktrace=never
app.username=${APP_USERNAME}
app.password=${APP_PASSWORD}
